### ISSUE TITLE
TODO Items

### ISSUE THREAD

**Issue by basejump** [9ci/grails-gorm-benchmarks#4]
- [x] update the Key conclusions
- [x] add the results for the autowiring in Bench Mark Results. describe what is being autowired
- [x] define system specs. 
- [x] define # of cores used with gpars
- [x] explain performance with gpars. if single thread is 1 core and gpars uses 4 cores then it should be about 4 times as fast?
- [x]  show screen shot of processor usage for fastest gpars test. 
- [x] allow this to run with H2 in memory db.
- [x] setup to run without validation as well as autowiring and show results
- [x] explain how to run this without "run-app" so it doesn't have reloading overhead. deploy to tomcat should not be needed. grail 3 and spring boot can bundle it into and executable jar
- [x] work out how we might do a warm up like here https://grails.github.io/grails-howtos/en/performanceTuning.html
- [x] log info on mem usage 

These can be done with fastest test I think to compare results

- [x] add in benchmark tests for how we are doing this at CED with the queue batching and scrolling. 
- [x] add benchmarks for the Grails out out of the box dateupdated and createdDate
- [x] add benchmark without the dao plugin
- [x] add benchmark with audit-trail

**Comment by snimavat** [comment]
@basejump have a look at readme
